In [70]:
#Importing needed Libraries
from mpl_toolkits.mplot3d import Axes3D
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from tkinter import *
import numpy as np
import pandas as pd
import os

In [71]:
#Here is the list of symptoms

l1=['Body back pain','constipation','abdominal pain','diarrhoea','mild_fever','yellowish urine',
    'yellowish eyes','liver damage','too much fluids in the blood','swelling of stomach',
    'swelled lymph nodes','malaise','Impaired vision','phlegm','Throat infections',
    'Redness of eyes','Nasal congestion','discharge mucus from the nose','Body stiffness','chest pain','weakness in limbs',
    'fast heart rate','pain during bowel movements','pain in anal region','bleeding with stool',
    'itching around the anus','neck pain','dizziness','cramps of body','bruising','obesity','swollen legs',
    'swollen blood vessels','puffy face and eyes','That the thyroid gland is large','brittle nails',
    'swelling of arms, feet, ankles, and legs','excessive hunger','Problems with unmarried relationships','drying and tingling lips',
    'slurred speech','knee pain','hip joint pain','muscle weakness','Tightness of the neck','swelling joints',
    'Tightness in body movements','Dizziness during movements','loss of body balance','Body unsteadiness',
    'weakness of one body side','loss of sense of smell','Pain in the bladder','foul smell of urine',
    'Need to urinate frequently','releasing gas through the anus','body internal itching','typhus fever',
    'depression','irritability','muscle pain','inability to think clearly or concentrate','red spots on body','lower stomach pain',
    'abnormal menstruation','Discolored skin','Tears in the eyes','Excessive hunger','production of abnormal volumes of urine','Hereditary disorders','white mucus come from the nose',
    'Rust-colored mucus come from the nose','overactivity','change in  eyesight','Transfusion Reactions',
    'unsafe injection','coma','bleeding in stomach','swelling of the abdomen',
    'high dosage of alcohol consumption','Excess fluid resulting in body weight gain','blood with mucus','swollen and enlarged veins that occur on the legs and feet',
    'feel like heart stopped beats','pain when walking','pus-filled pimples','blackheads','scurring','damage to the upper layer of your skin',
    'the skin turns blue or blue-grey','pitting in Nail','an inflammation of the skin around the nail','blister','Red skin under and around nose',
    'Yellowish crusting pus builds up']

In [72]:
#Here is the list of diseases

disease=['Fungal infection', 'Allergy', 'Gastroesophageal reflux disease (GERD)', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis disease', 'Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid(a bacterial infection)', 'hepatitis A',
       'Hepatitis B liver infection', 'Hepatitis C virus infection', 'Hepatitis D swelling liver', 'Hepatitis E (A liver disease)',
       'Alcoholic hepatitis (swelling of the liver)', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Swelling of the blood vessels in the rectum', 'Heart attack', 'Varicose veins',
       'Body doesn\'t produce enough thyroid hormones', 'Hyperthyroidism', 'Hypoglycemia(low blood sugar)',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo']


In [73]:
#read the dataset
df=pd.read_csv("training.csv")

DF= pd.read_csv('training.csv', index_col='prognosis')

#Replace the values in the imported file by pandas
df.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)

DF.head()

itching  skin_rash  nodal_skin_eruptions  \
prognosis                                                    
Fungal infection        1          1                     1   
Fungal infection        0          1                     1   
Fungal infection        1          0                     1   
Fungal infection        1          1                     0   
Fungal infection        1          1                     1   

                  continuous_sneezing  shivering  chills  joint_pain  \
prognosis                                                              
Fungal infection                    0          0       0           0   
Fungal infection                    0          0       0           0   
Fungal infection                    0          0       0           0   
Fungal infection                    0          0       0           0   
Fungal infection                    0          0       0           0   

                  stomach_pain  acidity  ulcers_on_tongue  ...  \
prognosis                                                  ...   
Fungal infection             0        0                 0  ...   
Fungal infection             0        0                 0  ...   
Fungal infection             0        0                 0  ...   
Fungal infection             0        0                 0  ...   
Fungal infection             0        0                 0  ...   

                  pus-filled pimples  blackheads  scurring  \
prognosis                                                    
Fungal infection                   0           0         0   
Fungal infection                   0           0         0   
Fungal infection                   0           0         0   
Fungal infection                   0           0         0   
Fungal infection                   0           0         0   

                  damage to the upper layer of your skin  \
prognosis                                                  
Fungal infection                                       0   
Fungal infection                                       0   
Fungal infection                                       0   
Fungal infection                                       0   
Fungal infection                                       0   

                  the skin turns blue or blue-grey  pitting in Nail  \
prognosis                                                             
Fungal infection                                 0                0   
Fungal infection                                 0                0   
Fungal infection                                 0                0   
Fungal infection                                 0                0   
Fungal infection                                 0                0   

                  an inflammation of the skin around the nail  blister  \
prognosis                                                                
Fungal infection                                            0        0   
Fungal infection                                            0        0   
Fungal infection                                            0        0   
Fungal infection                                            0        0   
Fungal infection                                            0        0   

                  Red skin under and around nose  \
prognosis                                          
Fungal infection                               0   
Fungal infection                               0   
Fungal infection                               0   
Fungal infection                               0   
Fungal infection                               0   

                  Yellowish crusting pus builds up  
prognosis                                           
Fungal infection                                 0  
Fungal infection                                 0  
Fungal infection                                 0  
Fungal infection                                 0  
Fungal infection                                 0  

[5 ro

In [74]:
X= df[l1]
y = df[["prognosis"]]
np.ravel(y)
print(X)

      Body back pain  constipation  abdominal pain  diarrhoea  mild_fever  \
0                  0             0               0          0           0   
1                  0             0               0          0           0   
2                  0             0               0          0           0   
3                  0             0               0          0           0   
4                  0             0               0          0           0   
...              ...           ...             ...        ...         ...   
4915               0             0               0          0           0   
4916               0             0               0          0           0   
4917               0             0               0          0           0   
4918               0             0               0          0           0   
4919               0             0               0          0           0   

      yellowish urine  yellowish eyes  liver damage  \
0                   

In [75]:
print(y)

      prognosis
0             0
1             0
2             0
3             0
4             0
...         ...
4915         36
4916         37
4917         38
4918         39
4919         40

[4920 rows x 1 columns]


In [76]:
#load testing data
tr=pd.read_csv("testing.csv")

In [77]:
tr.replace({'prognosis':{'Fungal infection':0,'Allergy':1,'GERD':2,'Chronic cholestasis':3,'Drug Reaction':4,
    'Peptic ulcer diseae':5,'AIDS':6,'Diabetes ':7,'Gastroenteritis':8,'Bronchial Asthma':9,'Hypertension ':10,
    'Migraine':11,'Cervical spondylosis':12,
    'Paralysis (brain hemorrhage)':13,'Jaundice':14,'Malaria':15,'Chicken pox':16,'Dengue':17,'Typhoid':18,'hepatitis A':19,
    'Hepatitis B':20,'Hepatitis C':21,'Hepatitis D':22,'Hepatitis E':23,'Alcoholic hepatitis':24,'Tuberculosis':25,
    'Common Cold':26,'Pneumonia':27,'Dimorphic hemmorhoids(piles)':28,'Heart attack':29,'Varicose veins':30,'Hypothyroidism':31,
    'Hyperthyroidism':32,'Hypoglycemia':33,'Osteoarthristis':34,'Arthritis':35,
    '(vertigo) Paroymsal  Positional Vertigo':36,'Acne':37,'Urinary tract infection':38,'Psoriasis':39,
    'Impetigo':40}},inplace=True)
tr.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          0                     0                    1          1   
2        0          0                     0                    0          0   
3        1          0                     0                    0          0   
4        1          1                     0                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       1           0             0        0                 0  ...   
2       0           0             1        1                 1  ...   
3       0           0             0        0                 0  ...   
4       0           0             1        0                 0  ...   

   blackheads  scurring  damage to the upper layer of your skin  \
0           0         0                                       0   
1           0         0                                       0   
2           0         0                                       0   
3           0         0                                       0   
4           0         0                                       0   

   the skin turns blue or blue-grey  pitting in Nail  \
0                                 0                0   
1                                 0                0   
2                                 0                0   
3                                 0                0   
4                                 0                0   

   an inflammation of the skin around the nail  blister  \
0                                            0        0   
1                                            0        0   
2                                            0        0   
3                                            0        0   
4                                            0        0   

   Red skin under and around nose  Yellowish crusting pus builds up  prognosis  
0                               0                                 0          0  
1                               0                                 0          1  
2                               0                                 0          2  
3                               0                                 0          3  
4                               0                                 0          4  

[5 rows x 133 columns]

In [78]:
X_test= tr[l1]
y_test = tr[["prognosis"]]
np.ravel(y_test)
print(X_test)

    Body back pain  constipation  abdominal pain  diarrhoea  mild_fever  \
0                0             0               0          0           0   
1                0             0               0          0           0   
2                0             0               0          0           0   
3                0             0               1          0           0   
4                0             0               0          0           0   
5                0             0               1          0           0   
6                0             0               0          0           0   
7                0             0               0          0           0   
8                0             0               0          1           0   
9                0             0               0          0           0   
10               0             0               0          0           0   
11               0             0               0          0           0   
12               1       

In [79]:
print(y_test)

    prognosis
0           0
1           1
2           2
3           3
4           4
5           5
6           6
7           7
8           8
9           9
10         10
11         11
12         12
13         13
14         14
15         15
16         16
17         17
18         18
19         19
20         20
21         21
22         22
23         23
24         24
25         25
26         26
27         27
28         28
29         29
30         30
31         31
32         32
33         33
34         34
35         35
36         36
37         37
38         38
39         39
40         40


In [80]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [81]:
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn=knn.fit(X,np.ravel(y))

In [82]:
y_pred=knn.predict(X_test)
print("Accuracy")
print(accuracy_score(y_test, y_pred))
print(accuracy_score(y_test, y_pred,normalize=False))
print("Confusion matrix")
conf_matrix=confusion_matrix(y_test,y_pred)
print(conf_matrix)

Accuracy
0.9512195121951219
39
Confusion matrix
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


In [83]:
import joblib

In [84]:
joblib.dump(knn,'KNNModel.pkl')

['KNNModel.pkl']